In [1]:
import pandas as pd

df1 = pd.read_csv(r"D:\datasets\PortfolioProjects-main\netflix_dataset\netflix_tv_shows_detailed_up_to_2025.csv")

df2 = pd.read_csv(r"D:\datasets\PortfolioProjects-main\netflix_dataset\netflix_movies_detailed_up_to_2025.csv")

In [2]:
main_df = pd.concat([df1, df2], ignore_index = True)

main_df['show_id'] = main_df['show_id'].astype(str)

main_df['show_id'] = main_df.apply(lambda row: f"M-{row['show_id']}" if row['type'] == 'Movie' else f"T-{row['show_id']}", axis=1)

main_df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,language,description,popularity,vote_count,vote_average,budget,revenue
0,T-33238,TV Show,Running Man,안재철,"Yoo Jae-suk, Jee Seok-jin, Kim Jong-kook, Haha...",South Korea,7/11/2010,2010,8.241,1 Seasons,"Comedy, Reality",ko,A reality and competition show where members a...,1929.898,187,8.241,NaN,NaN
1,T-32415,TV Show,Conan,NaN,"Conan O'Brien, Andy Richter",United States of America,11/8/2010,2010,7.035,1 Seasons,"Talk, Comedy, News",en,A late night television talk show hosted by C...,1670.580,229,7.035,NaN,NaN
2,T-37757,TV Show,MasterChef Greece,NaN,NaN,Greece,10/3/2010,2010,5.600,1 Seasons,Reality,el,MasterChef Greece is a Greek competitive cooki...,1317.092,6,5.600,NaN,NaN
3,T-75685,TV Show,Prostřeno!,NaN,"Václav Vydra, Jana Boušková",Czech Republic,3/1/2010,2010,6.500,1 Seasons,Reality,cs,The knives (and forks) are out as a group of s...,1095.776,6,6.500,NaN,NaN
4,T-33847,TV Show,The Talk,NaN,"Amanda Kloots, Jerry O'Connell, Akbar Gbaja-Bi...","United States of America, Ireland",10/18/2010,2010,3.400,1 Seasons,Talk,en,A panel of well-known news and entertainment p...,712.070,12,3.400,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31995,M-1440286,Movie,Festival de Viña del Mar 2025: Ha*Ash,NaN,Ha*ash,Chile,2/24/2025,2025,0.000,NaN,Music,es,NaN,4.931,0,0.000,0.0,0.0
31996,M-1271724,Movie,Man and Woman,Vladimir Kott,"Anna Kotova, Stepan Devonin, Pavel Derevyanko,...",Russia,3/13/2025,2025,0.000,NaN,Drama,ru,Poignant stories about men and women who have ...,4.930,0,0.000,0.0,0.0
31997,M-1426364,Movie,Night of the Dead Sorority Babes,"Angel Nichole Bradford, Steve Hermann","Jessa Flux, Lynn Lowry, Angel Nichole Bradford...",NaN,1/28/2025,2025,1.000,NaN,Horror,en,Two villainous entities initiate gorgeous soro...,4.922,1,1.000,0.0,0.0
31998,M-1411248,Movie,A Dunces Burden,Daniel Kowal,"Riley G, Mitchel Corrado",NaN,3/10/2025,2025,0.000,NaN,NaN,en,A Dunces Burden,4.921,0,0.000,0.0,0.0
31999,M-1405742,Movie,Portal to Hell,Woody Bess,"Trey Holland, Keith David, Richard Kind, Micha...",United States of America,2/22/2025,2025,0.000,NaN,"Comedy, Horror",en,After a debt-collector finds a portal to hell ...,4.921,0,0.000,0.0,0.0

In [3]:
main_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32000 entries, 0 to 31999
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       32000 non-null  object
 1   type          32000 non-null  object
 2   title         32000 non-null  object
 3   director      20903 non-null  object
 4   cast          30639 non-null  object
 5   country       29737 non-null  object
 6   date_added    32000 non-null  object
 7   release_year  32000 non-null  int64
 8   rating        32000 non-null  float64
 9   duration      16000 non-null  object
 10  genres        30919 non-null  object
 11  language      32000 non-null  object
 12  description   28662 non-null  object
 13  popularity    32000 non-null  float64
 14  vote_count    32000 non-null  int64
 15  vote_average  32000 non-null  float64
 16  budget        16000 non-null  float64
 17  revenue       16000 non-null  float64
dtypes: float64(5), int64(2), object(11)
memory usage: 4.4+ MB

In [4]:
bridge_df = main_df[['show_id', 'country']].copy()

bridge_df['country'] = bridge_df['country'].fillna('Unknown') 

bridge_df['country'] = bridge_df['country'].str.split(',')

bridge_df = bridge_df.explode('country')

bridge_df['country'] = bridge_df['country'].str.strip()

bridge_df

         show_id                   country
0        T-33238               South Korea
1        T-32415  United States of America
2        T-37757                    Greece
3        T-75685            Czech Republic
4        T-33847  United States of America
...          ...                       ...
31995  M-1440286                     Chile
31996  M-1271724                    Russia
31997  M-1426364                   Unknown
31998  M-1411248                   Unknown
31999  M-1405742  United States of America

[39899 rows x 2 columns]

In [5]:
main_df = main_df.drop(columns = 'country')

main_df

,show_id,type,title,director,cast,date_added,release_year,rating,duration,genres,language,description,popularity,vote_count,vote_average,budget,revenue
0,T-33238,TV Show,Running Man,안재철,"Yoo Jae-suk, Jee Seok-jin, Kim Jong-kook, Haha...",7/11/2010,2010,8.241,1 Seasons,"Comedy, Reality",ko,A reality and competition show where members a...,1929.898,187,8.241,NaN,NaN
1,T-32415,TV Show,Conan,NaN,"Conan O'Brien, Andy Richter",11/8/2010,2010,7.035,1 Seasons,"Talk, Comedy, News",en,A late night television talk show hosted by C...,1670.580,229,7.035,NaN,NaN
2,T-37757,TV Show,MasterChef Greece,NaN,NaN,10/3/2010,2010,5.600,1 Seasons,Reality,el,MasterChef Greece is a Greek competitive cooki...,1317.092,6,5.600,NaN,NaN
3,T-75685,TV Show,Prostřeno!,NaN,"Václav Vydra, Jana Boušková",3/1/2010,2010,6.500,1 Seasons,Reality,cs,The knives (and forks) are out as a group of s...,1095.776,6,6.500,NaN,NaN
4,T-33847,TV Show,The Talk,NaN,"Amanda Kloots, Jerry O'Connell, Akbar Gbaja-Bi...",10/18/2010,2010,3.400,1 Seasons,Talk,en,A panel of well-known news and entertainment p...,712.070,12,3.400,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31995,M-1440286,Movie,Festival de Viña del Mar 2025: Ha*Ash,NaN,Ha*ash,2/24/2025,2025,0.000,NaN,Music,es,NaN,4.931,0,0.000,0.0,0.0
31996,M-1271724,Movie,Man and Woman,Vladimir Kott,"Anna Kotova, Stepan Devonin, Pavel Derevyanko,...",3/13/2025,2025,0.000,NaN,Drama,ru,Poignant stories about men and women who have ...,4.930,0,0.000,0.0,0.0
31997,M-1426364,Movie,Night of the Dead Sorority Babes,"Angel Nichole Bradford, Steve Hermann","Jessa Flux, Lynn Lowry, Angel Nichole Bradford...",1/28/2025,2025,1.000,NaN,Horror,en,Two villainous entities initiate gorgeous soro...,4.922,1,1.000,0.0,0.0
31998,M-1411248,Movie,A Dunces Burden,Daniel Kowal,"Riley G, Mitchel Corrado",3/10/2025,2025,0.000,NaN,NaN,en,A Dunces Burden,4.921,0,0.000,0.0,0.0
31999,M-1405742,Movie,Portal to Hell,Woody Bess,"Trey Holland, Keith David, Richard Kind, Micha...",2/22/2025,2025,0.000,NaN,"Comedy, Horror",en,After a debt-collector finds a portal to hell ...,4.921,0,0.000,0.0,0.0

In [6]:
cast_df = main_df[['show_id', 'cast']].copy()

cast_df['cast'] = cast_df['cast'].fillna('Unknown') 

cast_df['cast'] = cast_df['cast'].str.split(',')

cast_df = cast_df.explode('cast')

cast_df['cast'] = cast_df['cast'].str.strip()


main_df = main_df.drop(columns = 'cast')

main_df

,show_id,type,title,director,date_added,release_year,rating,duration,genres,language,description,popularity,vote_count,vote_average,budget,revenue
0,T-33238,TV Show,Running Man,안재철,7/11/2010,2010,8.241,1 Seasons,"Comedy, Reality",ko,A reality and competition show where members a...,1929.898,187,8.241,NaN,NaN
1,T-32415,TV Show,Conan,NaN,11/8/2010,2010,7.035,1 Seasons,"Talk, Comedy, News",en,A late night television talk show hosted by C...,1670.580,229,7.035,NaN,NaN
2,T-37757,TV Show,MasterChef Greece,NaN,10/3/2010,2010,5.600,1 Seasons,Reality,el,MasterChef Greece is a Greek competitive cooki...,1317.092,6,5.600,NaN,NaN
3,T-75685,TV Show,Prostřeno!,NaN,3/1/2010,2010,6.500,1 Seasons,Reality,cs,The knives (and forks) are out as a group of s...,1095.776,6,6.500,NaN,NaN
4,T-33847,TV Show,The Talk,NaN,10/18/2010,2010,3.400,1 Seasons,Talk,en,A panel of well-known news and entertainment p...,712.070,12,3.400,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31995,M-1440286,Movie,Festival de Viña del Mar 2025: Ha*Ash,NaN,2/24/2025,2025,0.000,NaN,Music,es,NaN,4.931,0,0.000,0.0,0.0
31996,M-1271724,Movie,Man and Woman,Vladimir Kott,3/13/2025,2025,0.000,NaN,Drama,ru,Poignant stories about men and women who have ...,4.930,0,0.000,0.0,0.0
31997,M-1426364,Movie,Night of the Dead Sorority Babes,"Angel Nichole Bradford, Steve Hermann",1/28/2025,2025,1.000,NaN,Horror,en,Two villainous entities initiate gorgeous soro...,4.922,1,1.000,0.0,0.0
31998,M-1411248,Movie,A Dunces Burden,Daniel Kowal,3/10/2025,2025,0.000,NaN,NaN,en,A Dunces Burden,4.921,0,0.000,0.0,0.0
31999,M-1405742,Movie,Portal to Hell,Woody Bess,2/22/2025,2025,0.000,NaN,"Comedy, Horror",en,After a debt-collector finds a portal to hell ...,4.921,0,0.000,0.0,0.0

In [7]:
director_df = main_df[['show_id', 'director']].copy()

director_df['director'] = director_df['director'].fillna('Unknown') 

director_df['director'] = director_df['director'].str.split(',')

director_df = director_df.explode('director')

director_df['director'] = director_df['director'].str.strip()

main_df = main_df.drop(columns = 'director')

main_df

,show_id,type,title,date_added,release_year,rating,duration,genres,language,description,popularity,vote_count,vote_average,budget,revenue
0,T-33238,TV Show,Running Man,7/11/2010,2010,8.241,1 Seasons,"Comedy, Reality",ko,A reality and competition show where members a...,1929.898,187,8.241,NaN,NaN
1,T-32415,TV Show,Conan,11/8/2010,2010,7.035,1 Seasons,"Talk, Comedy, News",en,A late night television talk show hosted by C...,1670.580,229,7.035,NaN,NaN
2,T-37757,TV Show,MasterChef Greece,10/3/2010,2010,5.600,1 Seasons,Reality,el,MasterChef Greece is a Greek competitive cooki...,1317.092,6,5.600,NaN,NaN
3,T-75685,TV Show,Prostřeno!,3/1/2010,2010,6.500,1 Seasons,Reality,cs,The knives (and forks) are out as a group of s...,1095.776,6,6.500,NaN,NaN
4,T-33847,TV Show,The Talk,10/18/2010,2010,3.400,1 Seasons,Talk,en,A panel of well-known news and entertainment p...,712.070,12,3.400,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31995,M-1440286,Movie,Festival de Viña del Mar 2025: Ha*Ash,2/24/2025,2025,0.000,NaN,Music,es,NaN,4.931,0,0.000,0.0,0.0
31996,M-1271724,Movie,Man and Woman,3/13/2025,2025,0.000,NaN,Drama,ru,Poignant stories about men and women who have ...,4.930,0,0.000,0.0,0.0
31997,M-1426364,Movie,Night of the Dead Sorority Babes,1/28/2025,2025,1.000,NaN,Horror,en,Two villainous entities initiate gorgeous soro...,4.922,1,1.000,0.0,0.0
31998,M-1411248,Movie,A Dunces Burden,3/10/2025,2025,0.000,NaN,NaN,en,A Dunces Burden,4.921,0,0.000,0.0,0.0
31999,M-1405742,Movie,Portal to Hell,2/22/2025,2025,0.000,NaN,"Comedy, Horror",en,After a debt-collector finds a portal to hell ...,4.921,0,0.000,0.0,0.0

In [8]:
genres_df = main_df[['show_id', 'genres']].copy()

genres_df['genres'] = genres_df['genres'].fillna('Unknown') 

genres_df['genres'] = genres_df['genres'].str.split(',')

genres_df = genres_df.explode('genres')

genres_df['genres'] = genres_df['genres'].str.strip()

main_df = main_df.drop(columns = 'genres')

genres_df

         show_id   genres
0        T-33238   Comedy
0        T-33238  Reality
1        T-32415     Talk
1        T-32415   Comedy
1        T-32415     News
...          ...      ...
31996  M-1271724    Drama
31997  M-1426364   Horror
31998  M-1411248  Unknown
31999  M-1405742   Comedy
31999  M-1405742   Horror

[66994 rows x 2 columns]

In [9]:
main_df[['budget', 'revenue']].isna().sum()
(main_df[['budget', 'revenue']] > 0).sum()

(main_df[['budget', 'revenue']].isna().mean() * 100).round(2)

main_df['budget'].info()

main_df[['vote_count', 'vote_average', 'popularity']].isna().sum()

<class 'pandas.core.series.Series'>
RangeIndex: 32000 entries, 0 to 31999
Series name: budget
Non-Null Count  Dtype
--------------  -----
16000 non-null  float64
dtypes: float64(1)
memory usage: 250.1 KB

vote_count      0
vote_average    0
popularity      0
dtype: int64

In [10]:
print(main_df.shape)
print(main_df.dtypes)

(32000, 14)
show_id          object
type             object
title            object
date_added       object
release_year      int64
rating          float64
duration         object
language         object
description      object
popularity      float64
vote_count        int64
vote_average    float64
budget          float64
revenue         float64
dtype: object

In [11]:
main_df['description'] = main_df['description'].fillna('Description not available')

main_df['duration'] = main_df['duration'].fillna('Unknown')
main_df

,show_id,type,title,date_added,release_year,rating,duration,language,description,popularity,vote_count,vote_average,budget,revenue
0,T-33238,TV Show,Running Man,7/11/2010,2010,8.241,1 Seasons,ko,A reality and competition show where members a...,1929.898,187,8.241,NaN,NaN
1,T-32415,TV Show,Conan,11/8/2010,2010,7.035,1 Seasons,en,A late night television talk show hosted by C...,1670.580,229,7.035,NaN,NaN
2,T-37757,TV Show,MasterChef Greece,10/3/2010,2010,5.600,1 Seasons,el,MasterChef Greece is a Greek competitive cooki...,1317.092,6,5.600,NaN,NaN
3,T-75685,TV Show,Prostřeno!,3/1/2010,2010,6.500,1 Seasons,cs,The knives (and forks) are out as a group of s...,1095.776,6,6.500,NaN,NaN
4,T-33847,TV Show,The Talk,10/18/2010,2010,3.400,1 Seasons,en,A panel of well-known news and entertainment p...,712.070,12,3.400,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31995,M-1440286,Movie,Festival de Viña del Mar 2025: Ha*Ash,2/24/2025,2025,0.000,Unknown,es,Description not available,4.931,0,0.000,0.0,0.0
31996,M-1271724,Movie,Man and Woman,3/13/2025,2025,0.000,Unknown,ru,Poignant stories about men and women who have ...,4.930,0,0.000,0.0,0.0
31997,M-1426364,Movie,Night of the Dead Sorority Babes,1/28/2025,2025,1.000,Unknown,en,Two villainous entities initiate gorgeous soro...,4.922,1,1.000,0.0,0.0
31998,M-1411248,Movie,A Dunces Burden,3/10/2025,2025,0.000,Unknown,en,A Dunces Burden,4.921,0,0.000,0.0,0.0
31999,M-1405742,Movie,Portal to Hell,2/22/2025,2025,0.000,Unknown,en,After a debt-collector finds a portal to hell ...,4.921,0,0.000,0.0,0.0

In [12]:
main_df[['budget','revenue']] = main_df[['budget','revenue']].fillna('0')
main_df[['budget','revenue']]

      budget revenue
0          0       0
1          0       0
2          0       0
3          0       0
4          0       0
...      ...     ...
31995    0.0     0.0
31996    0.0     0.0
31997    0.0     0.0
31998    0.0     0.0
31999    0.0     0.0

[32000 rows x 2 columns]

In [13]:
main_df['date_added'] = pd.to_datetime(main_df['date_added'], errors='coerce')
main_df['date_added'].info()

main_df

<class 'pandas.core.series.Series'>
RangeIndex: 32000 entries, 0 to 31999
Series name: date_added
Non-Null Count  Dtype
--------------  -----
32000 non-null  datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 250.1 KB

,show_id,type,title,date_added,release_year,rating,duration,language,description,popularity,vote_count,vote_average,budget,revenue
0,T-33238,TV Show,Running Man,2010-07-11,2010,8.241,1 Seasons,ko,A reality and competition show where members a...,1929.898,187,8.241,0,0
1,T-32415,TV Show,Conan,2010-11-08,2010,7.035,1 Seasons,en,A late night television talk show hosted by C...,1670.580,229,7.035,0,0
2,T-37757,TV Show,MasterChef Greece,2010-10-03,2010,5.600,1 Seasons,el,MasterChef Greece is a Greek competitive cooki...,1317.092,6,5.600,0,0
3,T-75685,TV Show,Prostřeno!,2010-03-01,2010,6.500,1 Seasons,cs,The knives (and forks) are out as a group of s...,1095.776,6,6.500,0,0
4,T-33847,TV Show,The Talk,2010-10-18,2010,3.400,1 Seasons,en,A panel of well-known news and entertainment p...,712.070,12,3.400,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31995,M-1440286,Movie,Festival de Viña del Mar 2025: Ha*Ash,2025-02-24,2025,0.000,Unknown,es,Description not available,4.931,0,0.000,0.0,0.0
31996,M-1271724,Movie,Man and Woman,2025-03-13,2025,0.000,Unknown,ru,Poignant stories about men and women who have ...,4.930,0,0.000,0.0,0.0
31997,M-1426364,Movie,Night of the Dead Sorority Babes,2025-01-28,2025,1.000,Unknown,en,Two villainous entities initiate gorgeous soro...,4.922,1,1.000,0.0,0.0
31998,M-1411248,Movie,A Dunces Burden,2025-03-10,2025,0.000,Unknown,en,A Dunces Burden,4.921,0,0.000,0.0,0.0
31999,M-1405742,Movie,Portal to Hell,2025-02-22,2025,0.000,Unknown,en,After a debt-collector finds a portal to hell ...,4.921,0,0.000,0.0,0.0

In [16]:
import urllib.parse
from sqlalchemy import create_engine

# 1. Type your password here safely

raw_password = 'dbz@54321'

# 2. This safely encodes your password so special characters don't break the connection URL
encoded_password = urllib.parse.quote_plus(raw_password)

# 3. Create the direct connection string to your 'netflix' database
DATABASE_URL = f"postgresql://postgres:{encoded_password}@localhost:5432/netflix"

# 4. Build the engine
engine = create_engine(DATABASE_URL)
print("✅ Python successfully connected to the PostgreSQL 'netflix' database!")

✅ Python successfully connected to the PostgreSQL 'netflix' database!

In [17]:
print("Starting data migration to PostgreSQL...")

# 1. Export the main Fact Table
main_df.to_sql(name='netflix_titles', con=engine, if_exists='replace', index=False)
print("-> 'netflix_titles' table exported successfully.")

# 2. Export the Countries Bridge Table (Using your bridge_df)
bridge_df.to_sql(name='show_countries', con=engine, if_exists='replace', index=False)
print("-> 'show_countries' table exported successfully.")

# 3. Export the Cast Bridge Table (Using your cast_df)
cast_df.to_sql(name='show_cast', con=engine, if_exists='replace', index=False)
print("-> 'show_cast' table exported successfully.")

# 4. Export the Directors Bridge Table
director_df.to_sql(name='show_directors', con=engine, if_exists='replace', index=False)
print("-> 'show_directors' table exported successfully.")

# 5. Export the Genres Bridge Table
genres_df.to_sql(name='show_genres', con=engine, if_exists='replace', index=False)
print("-> 'show_genres' table exported successfully.")

print("\n🎉 ALL TABLES SUCCESSFULLY MIGRATED TO POSTGRESQL!")

Starting data migration to PostgreSQL...
-> 'netflix_titles' table exported successfully.
-> 'show_countries' table exported successfully.
-> 'show_cast' table exported successfully.
-> 'show_directors' table exported successfully.
-> 'show_genres' table exported successfully.

🎉 ALL TABLES SUCCESSFULLY MIGRATED TO POSTGRESQL!